variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
variable "Okit_Comp001_display_name" {}
variable "Okit_Comp001_description" {}
variable "Okit_Vcn001_cidr_block" {}
variable "Okit_Vcn001_display_name" {}
variable "Okit_Vcn001_dns_label" {}
variable "Okit_Ig001_display_name" {}
variable "Okit_Ig001_enabled" {}
variable "Okit_Ng001_display_name" {}
variable "Okit_Ng001_block_traffic" {}
variable "Okit_Sl001_display_name" {}
variable "Okit_Sl001_egress_rule_01_protocol" {}
variable "Okit_Sl001_egress_rule_01_destination" {}
variable "Okit_Sl001_egress_rule_01_destination_type" {}
variable "Okit_Sl001_egress_rule_01_description" {}
variable "Okit_Sl001_ingress_rule_01_protocol" {}
variable "Okit_Sl001_ingress_rule_01_tcp_dst_min" {}
variable "Okit_Sl001_ingress_rule_01_tcp_dst_max" {}
variable "Okit_Sl001_ingress_rule_01_source_type" {}
variable "Okit_Sl001_ingress_rule_01_source" {}
variable "Okit_Sl001_ingress_rule_01_description" {}
variable "Okit_Sl001_ingress_rule_02_protocol" {}
variable "Okit_Sl001_ingress_rule_02_icmp_type" {}
variable "Okit_Sl001_ingress_rule_02_icmp_code" {}
variable "Okit_Sl001_ingress_rule_02_source_type" {}
variable "Okit_Sl001_ingress_rule_02_source" {}
variable "Okit_Sl001_ingress_rule_02_description" {}
variable "Okit_Sl001_ingress_rule_03_protocol" {}
# variable "Okit_Sl001_ingress_rule_03_icmp_type" {}
variable "Okit_Sl001_ingress_rule_03_source_type" {}
variable "Okit_Sl001_ingress_rule_03_source" {}
variable "Okit_Sl001_ingress_rule_03_description" {}
variable "Secuprivate_display_name" {}
variable "Okit_Rt001_display_name" {}
variable "Okit_Rt001_route_rule_01_network_entity_id" {}
variable "Okit_Rt001_route_rule_01_destination" {}
variable "Okit_Rt001_route_rule_01_destination_type" {}
variable "Okit_Rt001_route_rule_01_description" {}
variable "Okit_Rt002_display_name" {}
variable "Okit_Rt002_route_rule_01_network_entity_id" {}
variable "Okit_Rt002_route_rule_01_destination" {}
variable "Okit_Rt002_route_rule_01_destination_type" {}
variable "Okit_Rt002_route_rule_01_description" {}
variable "Okit_Sn001_display_name" {}
variable "Okit_Sn001_cidr_block" {}
variable "Okit_Sn001_dns_label" {}
variable "Okit_Sn001_prohibit_public_ip_on_vnic" {}
variable "Subprivate_display_name" {}
variable "Subprivate_cidr_block" {}
variable "Subprivate_dns_label" {}
variable "Subprivate_prohibit_public_ip_on_vnic" {}
variable "Okit_Sn003_display_name" {}
variable "Okit_Sn003_cidr_block" {}
variable "Okit_Sn003_dns_label" {}
variable "Okit_Sn003_prohibit_public_ip_on_vnic" {}
variable "Okit_In001_availability_domain" {}
variable "Okit_In001_display_name" {}
variable "Okit_In001_shape" {}
variable "Okit_In001_source_type" {}
variable "Okit_In001_os" {}
variable "Okit_In001_os_version" {}
variable "Okit_In001_boot_volume_size_in_gbs" {}
variable "Okit_In001_display_name_vnic" {}
variable "Okit_In001_hostname_label" {}
variable "Okit_In001_primary_vnic_assign_public" {}
variable "Okit_In001_primary_vnic_skip_src_dst_check" {}
variable "Okit_In001_authorized_keys" {}
variable "ssh_private_key" {}
variable "Okit_In001_user_data" {}
variable "Okit_In001_fault_domain" {}
variable "Okit_In001_preserve_boot_volume" {}
variable "Okit_In002_availability_domain" {}
variable "Okit_In002_display_name" {}
variable "Okit_In002_shape" {}
variable "Okit_In002_source_type" {}
variable "Okit_In002_os" {}
variable "Okit_In002_os_version" {}
variable "Okit_In002_boot_volume_size_in_gbs" {}
variable "Okit_In002_display_name_vnic" {}
variable "Okit_In002_hostname_label" {}
variable "Okit_In002_primary_vnic_assign_public" {}
variable "Okit_In002_primary_vnic_skip_src_dst_check" {}
variable "Okit_In002_authorized_keys" {}
variable "Okit_In002_user_data" {}
variable "Okit_In002_fault_domain" {}
variable "Okit_In002_preserve_boot_volume" {}
variable "Okit_In003_availability_domain" {}
variable "Okit_In003_display_name" {}
variable "Okit_In003_shape" {}
variable "Okit_In003_source_type" {}
variable "Okit_In003_os" {}
variable "Okit_In003_os_version" {}
variable "Okit_In003_boot_volume_size_in_gbs" {}
variable "Okit_In003_display_name_vnic" {}
variable "Okit_In003_hostname_label" {}
variable "Okit_In003_primary_vnic_assign_public" {}
variable "Okit_In003_primary_vnic_skip_src_dst_check" {}
variable "Okit_In003_authorized_keys" {}
variable "Okit_In003_user_data" {}
variable "Okit_In003_fault_domain" {}
variable "Okit_In003_preserve_boot_volume" {}
variable "Okit_In004_availability_domain" {}
variable "Okit_In004_display_name" {}
variable "Okit_In004_shape" {}
variable "Okit_In004_source_type" {}
variable "Okit_In004_os" {}
variable "Okit_In004_os_version" {}
variable "Okit_In004_boot_volume_size_in_gbs" {}
variable "Okit_In004_display_name_vnic" {}
variable "Okit_In004_hostname_label" {}
variable "Okit_In004_primary_vnic_assign_public" {}
variable "Okit_In004_primary_vnic_skip_src_dst_check" {}
variable "Okit_In004_authorized_keys" {}
variable "Okit_In004_user_data" {}
variable "Okit_In004_fault_domain" {}
variable "Okit_In004_preserve_boot_volume" {}
variable "Okit_Lb001_display_name" {}
variable "Okit_Lb001_shape" {}
variable "Okit_Lb001_protocol" {}
variable "Okit_Lb001_backend_policy" {}
variable "Okit_Lb001_url_path" {}
